version: '3.8'

services:
  blockchain:
    build: .
    working_dir: /app
    command: npx hardhat node
    ports:
      - "8545:8545"
    volumes:
      - .:/app

  deploy:
    build: .
    depends_on:
      - blockchain
    command: >
      sh -c "sleep 5 && 
             npx hardhat compile &&
             npx hardhat run scripts/deploy.cjs --network localhost"
    volumes:
      - .:/app

  frontend:
    build: .
    working_dir: /app
    command: npm run dev
    depends_on:
      - deploy
    ports:
      - "5173:5173"
    volumes:
      - .:/app